### PR TITLE
Cu 37yvq52 compile tina as game to run unit tests and stories

### PR DESCRIPTION
**Pull request by adam-drake1**
This only changes necessary files so should be able to be merged into existing branches without issue to run unit tests.

### CODE REVIEW

**Comment by RigidStudios** [comment]
Task linked: [CU-37yvq52 Compile Tina as game to run unit tests and stories](https://app.clickup.com/t/37yvq52)

**Review by christopher-buss — COMMENTED** [review]
Looks good to me 👍🏻

**Comment by RigidStudios** [comment]
This looks good on my end, has it been tested and does it work?

**Review by RigidStudios — APPROVED** [review]
Nothing to say, this is ready for merge.

**Pull request merged**
